// <auto-generated />
namespace Clarksons.Cloud.Logging.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeToFloat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeToFloat));
        
        string IMigrationMetadata.Id
        {
            get { return "201810081143333_changeToFloat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
